spring:
  application:
    name: Order
    cors.allowed-origins: ${FRONTEND_URL}
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/order_db
    username: postgres
    password: postgres
  flyway:
    url: jdbc:postgresql://localhost:5432/order_db
    locations: classpath:db/postgres/migration

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KC_BASE_URL}/realms/storehub
          jwk-set-uri: ${KC_BASE_URL}/realms/storehub/protocol/openid-connect/certs

      client:
        registration:   # this name = "credentials used when calling catalog or any other internal service"
          keycloak-admin:
            provider: storehub-keycloak
            client-id: order-admin
            client-secret: ${KC_ADMIN_CLIENT_SECRET}
            authorization-grant-type: client_credentials
            scope: openid
          internal-service:
            provider: storehub-keycloak
            client-id: order-internal
            client-secret: ${ORDER_INTERNAL_SECRET}
            authorization-grant-type: client_credentials
        provider:
          storehub-keycloak:
            token-uri: ${KC_BASE_URL}/realms/storehub/protocol/openid-connect/token

storehub:
  internal-client-registration: internal-service
  admin-client-registration: keycloak-admin
  catalog-base-url: ${CATALOG_BASE_URL}
  kc-base-url: ${KC_BASE_URL}
  realm: storehub



external:
  product:
    api:
      base-url: http://localhost:3000
  slot:
    api:
      base-url: http://localhost:3030
  pricing:
    api:
      base-url: http://localhost:3060