version: '3'
services:

  product:
    image: wiremock/wiremock:3.3.1
    ports:
      - 3000:3000
    volumes:
      - /home/abdelkhalek-saadani/Desktop/Order/oms-order/order/src/test/resources/mappings/product:/home/wiremock/mappings
      - /home/abdelkhalek-saadani/Desktop/Order/oms-order/order/src/test/resources/__files/templates/product:/home/wiremock/__files/templates/product
    command: ['--port','3000','--global-response-templating']
  slot:
    image: wiremock/wiremock:3.3.1
    ports:
      - 3030:3030
    volumes:
      - /home/abdelkhalek-saadani/Desktop/Order/oms-order/order/src/test/resources/mappings/slot:/home/wiremock/mappings
      - /home/abdelkhalek-saadani/Desktop/Order/oms-order/order/src/test/resources/__files/templates/slot:/home/wiremock/__files/templates/slot
    command: [ '--port','3030','--global-response-templating' ]
  pricing:
    image: wiremock/wiremock:3.3.1
    ports:
      - 3060:3060
    volumes:
      - /home/abdelkhalek-saadani/Desktop/Order/oms-order/order/src/test/resources/mappings/pricing:/home/wiremock/mappings
    command: [ '--port','3060']